### ISSUE TITLE
cf: Add support for control flow lowering.

### ISSUE THREAD

**Issue by xlauko** [trailofbits/vast#29]
Implement lowering to [standard dialect](https://mlir.llvm.org/docs/Dialects/Standard/) of high level control flow structures from:

https://github.com/trailofbits/vast/blob/master/include/vast/Dialect/HighLevel/HighLevelCF.td

- [x] `hl::IfOp`
- [ ] `hl::WhileOp`
- [ ] `hl::ForOp`
- [ ] `hl::DoOp`
- [ ] `hl::BreakOp`
- [ ] `hl::ContinueOp`
- [ ] `hl::SwitchOp`, `hl::CaseOp`, `hl::DefaultOp`

Facade of `LowerControlFlowPass` is prepared here:

https://github.com/trailofbits/vast/blob/master/lib/vast/Dialect/HighLevel/Transforms/LowerControlFlow.cpp

To run control flow lowering use vast-opt tool on high-level mlir:

`vast-opt -vast-hl-lower-cf <file.mlir>`

To transform source directly pipe result from `vast` compiler:

`vast-cc --from-source <source.c> | vast-opt -vast-hl-lower-cf`

**Comment by lkorenc** [comment]
Instead of fully supporting lowering to `SCF` it is now planned to lower via `ll` dialect. Unfortunately `SCF` does not model some things (such as `if` with `return` in one of its branches) as we would like and therefore is not really usable.

There is nothing preventing or obscuring implementing this transformation where it makes sense, but in the pipeline `hl -> llvm` we are not going to use it.
